# openapi2-functions.yaml
    swagger: '2.0'
    info:
      title: clients-folders-03
      description: API Gateway with a Google Cloud Functions backend
      version: 2.0.0
    schemes:
      - https
    produces:
      - application/json
    paths:
      /createFolder:
        post:
          summary: Create client folder
          operationId: folderCreate
          x-google-backend:
            address: https://us-west1-zdrive-342222.cloudfunctions.net/function-03
          security:
          - api_key: []
          responses:
            '200':
              description: A successful response
              schema:
                type: string
    securityDefinitions:
      # This section configures basic authentication with an API key.
      api_key:
        type: "apiKey"
        name: "key"
        in: "query"
    